name: Build (SBT)

on:
  push:
    branches-ignore:
      master # we run deploy-gh-pages on master, no need to run just a build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Run tests
        run: sbt products
