name: Build (SBT)

on:
  push:
    branches-ignore:
      master # we run deploy-gh-pages on master, no need to run just a build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: sbt products
