name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: |
          sbt products
          mkdir public
          cp frontend/target/scala-2.12/*.js public/.
          cp frontend/target/scala-2.12/*.html public/.
          cp frontend/target/scala-2.12/*.css public/.
          mv public/index-fast.html public/index.html
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_USERTOKEN }}
