name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_USERTOKEN }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: |
          # call products to make sure css is built
          sbt products frontend/fullOptJS
          mkdir public
          cp frontend/target/scala-2.13/*-opt.js public/.
          cp frontend/target/scala-2.13/*-jsdeps.js public/.
          cp frontend/target/scala-2.13/index.html public/.
          cp frontend/target/scala-2.13/*.css public/.
          cp frontend/target/scala-2.13/*.svg public/.
          cp frontend/target/scala-2.13/favicon.ico public/.
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_USERTOKEN }}
