name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build
        run: |
          # call products to make sure css is built
          sbt products frontend/fullOptJS
          mkdir public
          cp frontend/target/scala-2.13/*-opt.js public/.
          cp frontend/target/scala-2.13/*-jsdeps.js public/.
          cp frontend/target/scala-2.13/index.html public/.
          cp frontend/target/scala-2.13/*.css public/.
          cp frontend/target/scala-2.13/*.svg public/.
          cp frontend/target/scala-2.13/favicon.ico public/.
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public

        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
